### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by federico-razzoli** [luiscontrerasdo/golang-mariadbconsole#1]
Without a license, all rights are automatically reserved. Many people don't know this, and might think that the software is open source or even in the public domain.

Please add a license, preferably an open source license.

**Comment by luiscontrerasdo** [comment]
Thanks @federico-razzoli for the suggestion, the license has been added.

**Comment by federico-razzoli** [comment]
Thanks @luiscontrerasdo! I'm closing the issue.

This repo is listed [here](https://github.com/Vettabase/awesome-mariadb/blob/main/list-dba.md). I updated the license.
